import { Language } from '../types';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'PRAHARI',
    tagline: 'Offline, Non-Invasive Early-Warning Screening System',
    roleAWW: 'Anganwadi Worker (Mobile)',
    roleSupervisor: 'Sector Supervisor',
    roleDistrictAdmin: 'District Administrator',
    disclaimer: 'This screening result does not replace confirmatory clinical testing.',
    demoDataNotice: 'DEMONSTRATION DATA — NOT CLINICAL DATA',
    screenedToday: 'Screened Today',
    highRiskCases: 'High-Risk Cases',
    followupsDue: 'Follow-ups Due',
    weeklyCoverage: 'Weekly Coverage',
    newScreening: 'New Screening',
    beneficiaries: 'Beneficiaries',
    followUps: 'Follow-ups',
    trajectory: 'Risk Trajectory',
    improving: 'Improving',
    stable: 'Stable',
    declining: 'Declining',
    rapidlyDeclining: 'Rapidly Declining',
    anemiaRisk: 'Anemia Risk',
    nutritionRisk: 'Nutrition Risk',
    overallPriority: 'Overall Priority',
    low: 'Low',
    moderate: 'Moderate',
    elevated: 'Elevated',
    high: 'High',
    synced: 'Synced',
    offline: 'Offline (Saved locally)',
    syncing: 'Syncing...',
    retakeImage: 'Retake Image',
    useImage: 'Use Image',
    goodQuality: 'Image quality: GOOD',
    insufficientQuality: 'Image quality insufficient',
    qualityBlur: 'Blur detected',
    qualityGlare: 'Glare / Reflection',
    qualityLighting: 'Poor lighting',
    qualityFraming: 'Incorrect framing',
    qualityMotion: 'Subject motion',
    weight: 'Weight (kg)',
    height: 'Height / Length (cm)',
    muac: 'MUAC (cm)',
    startAnalysis: 'Run Multimodal Analysis',
    analysisProgress: 'Combining screening signals...',
    recommendedAction: 'Recommended Next Step',
    flagReferral: 'Flag for PHC Referral',
    scheduleFollowup: 'Schedule 14-Day Follow-Up',
  },
  hi: {
    appTitle: 'प्रहरी (PRAHARI)',
    tagline: 'ऑफ़लाइन, गैर-आक्रामक प्रारंभिक चेतावनी जांच प्रणाली',
    roleAWW: 'आंगनवाड़ी कार्यकर्ता (मोबाइल)',
    roleSupervisor: 'सेक्टर पर्यवेक्षक',
    roleDistrictAdmin: 'जिला स्वास्थ्य प्रशासक',
    disclaimer: 'यह जांच परिणाम नैदानिक ​​परीक्षण (लैब टेस्ट) का स्थान नहीं लेता है।',
    demoDataNotice: 'प्रदर्शन डेटा — नैदानिक डेटा नहीं',
    screenedToday: 'आज की जांच',
    highRiskCases: 'उच्च जोखिम वाले मामले',
    followupsDue: 'फॉलो-अप देय',
    weeklyCoverage: 'साप्ताहिक कवरेज',
    newScreening: 'नई जांच',
    beneficiaries: 'लाभार्थी',
    followUps: 'फॉलो-अप',
    trajectory: 'जोखिम प्रक्षेपवक्र (ट्रेंड)',
    improving: 'सुधार हो रहा है',
    stable: 'स्थिर',
    declining: 'गिरावट',
    rapidlyDeclining: 'तेजी से गिरावट',
    anemiaRisk: 'एनीमिया जोखिम',
    nutritionRisk: 'पोषण जोखिम',
    overallPriority: 'कुल प्राथमिकता',
    low: 'कम',
    moderate: 'मध्यम',
    elevated: 'ऊंचा',
    high: 'उच्च',
    synced: 'सिंक हो गया',
    offline: 'ऑफ़लाइन (स्थानीय रूप से सहेजा गया)',
    syncing: 'सिंक हो रहा है...',
    retakeImage: 'पुनः फोटो लें',
    useImage: 'इस फोटो का उपयोग करें',
    goodQuality: 'छवि गुणवत्ता: अच्छी',
    insufficientQuality: 'छवि गुणवत्ता अपर्याप्त',
    qualityBlur: 'धुंधलापन',
    qualityGlare: 'चमक / परावर्तन',
    qualityLighting: 'खराब रोशनी',
    qualityFraming: 'गलत फ्रेमिंग',
    qualityMotion: 'गति (मोशन)',
    weight: 'वजन (किग्रा)',
    height: 'ऊंचाई (सेमी)',
    muac: 'एमयूएसी (सेमी)',
    startAnalysis: 'मल्टीमॉडल विश्लेषण चलाएं',
    analysisProgress: 'स्क्रीनिंग संकेतों का संयोजन...',
    recommendedAction: 'अनुशंसित अगला कदम',
    flagReferral: 'प्राथमिक स्वास्थ्य केंद्र (PHC) रेफरल करें',
    scheduleFollowup: '14-दिवसीय फॉलो-अप शेड्यूल करें',
  },
  ta: {
    appTitle: 'பிரஹாரி (PRAHARI)',
    tagline: 'ஆஃப்லைன், ஆக்கிரமிப்பற்ற முன் எச்சரிக்கை பரிசோதனை',
    roleAWW: 'அங்கன்வாடி பணியாளர் (மொபைல்)',
    roleSupervisor: 'துறை மேற்பார்வையாளர்',
    roleDistrictAdmin: 'மாவட்ட சுகாதார நிர்வாகி',
    disclaimer: 'இந்த பரிசோதனை முடிவு ஆய்வக பரிசோதனைக்கு மாற்றாகாது.',
    demoDataNotice: 'மாதிரி தரவு — மருத்துவ தரவு அல்ல',
    screenedToday: 'இன்று பரிசோதிக்கப்பட்டவர்கள்',
    highRiskCases: 'அதிக ஆபத்து வழக்குகள்',
    followupsDue: 'பின் தொடர வேண்டியவை',
    weeklyCoverage: 'வாராந்திர கவரேஜ்',
    newScreening: 'புதிய பரிசோதனை',
    beneficiaries: 'பயனாளிகள்',
    followUps: 'ஃபாலோ-அப்கள்',
    trajectory: 'ஆபத்து போக்கு',
    improving: 'மேம்படுகிறது',
    stable: 'சீராக உள்ளது',
    declining: 'குறைந்து வருகிறது',
    rapidlyDeclining: 'வேகமாக குறைகிறது',
    anemiaRisk: 'இரத்த சோகை ஆபத்து',
    nutritionRisk: 'ஊட்டச்சத்து ஆபத்து',
    overallPriority: 'ஒட்டுமொத்த முன்னுரிமை',
    low: 'குறைவு',
    moderate: 'மிதமான',
    elevated: 'உயர்ந்த',
    high: 'அதிகம்',
    synced: 'ஒத்திசைக்கப்பட்டது',
    offline: 'ஆஃப்லைன் (சேமிக்கப்பட்டது)',
    syncing: 'ஒத்திசைக்கப்படுகிறது...',
    retakeImage: 'மீண்டும் படம் எடுக்கவும்',
    useImage: 'படத்தைப் பயன்படுத்தவும்',
    goodQuality: 'படத் தரம்: நல்லது',
    insufficientQuality: 'படத் தரம் போதாது',
    qualityBlur: 'மங்கலானது',
    qualityGlare: 'வெளிச்சப் பிரதிபலிப்பு',
    qualityLighting: 'போதிய வெளிச்சமின்மை',
    qualityFraming: 'தவறான வடிவம்',
    qualityMotion: 'அசைவு',
    weight: 'எடை (கிலோ)',
    height: 'உயரம் (செமீ)',
    muac: 'MUAC (செமீ)',
    startAnalysis: 'பகுப்பாய்வு செய்',
    analysisProgress: 'சிக்னல்களை பகுப்பாய்வு செய்கிறது...',
    recommendedAction: 'பரிந்துரைக்கப்பட்ட அடுத்த நடவடிக்கை',
    flagReferral: 'PHC பரிந்துரைக்கு கொடியிடு',
    scheduleFollowup: '14 நாள் பின்தொடர்வை திட்டமிடு',
  },
  mr: {
    appTitle: 'प्रहरी (PRAHARI)',
    tagline: 'ऑफलाइन, विना-शस्त्रक्रिया पूर्व-इशारा तपासणी प्रणाली',
    roleAWW: 'अंगणवाडी सेविका (मोबाईल)',
    roleSupervisor: 'सेक्टर पर्यवेक्षक',
    roleDistrictAdmin: 'जिल्हा आरोग्य प्रशासक',
    disclaimer: 'हा तपासणी निकाल प्रयोगशाळा चाचणीचा पर्याय नाही.',
    demoDataNotice: 'प्रात्यक्षिक डेटा — वैद्यकीय डेटा नाही',
    screenedToday: 'आज तपासलेले',
    highRiskCases: 'उच्च धोका प्रकरणे',
    followupsDue: 'फॉलो-अप देय',
    weeklyCoverage: 'साप्ताहिक कव्हरेज',
    newScreening: 'नवीन तपासणी',
    beneficiaries: 'लाभार्थी',
    followUps: 'फॉलो-अप',
    trajectory: 'धोका प्रक्षेपवक्र (ट्रेंड)',
    improving: 'सुधारणा होत आहे',
    stable: 'स्थिर',
    declining: 'घसरण',
    rapidlyDeclining: 'वेगाने घसरण',
    anemiaRisk: 'अ‍ॅनिमिया धोका',
    nutritionRisk: 'पोषण धोका',
    overallPriority: 'एकूण प्राधान्य',
    low: 'कमी',
    moderate: 'मध्यम',
    elevated: 'उंच',
    high: 'उच्च',
    synced: 'सिंक झाले',
    offline: 'ऑफलाइन (स्थानिक पातळीवर जतन केले)',
    syncing: 'सिंक होत आहे...',
    retakeImage: 'पुन्हा फोटो घ्या',
    useImage: 'हा फोटो वापरा',
    goodQuality: 'फोटो गुणवत्ता: उत्तम',
    insufficientQuality: 'फोटो गुणवत्ता अपुरी',
    qualityBlur: 'धुरकटपणा',
    qualityGlare: 'चकाकी / परावर्तन',
    qualityLighting: 'कमी प्रकाश',
    qualityFraming: 'चुकीचे फ्रेमिंग',
    qualityMotion: 'हालचाल',
    weight: 'वजन (किग्रा)',
    height: 'उंच (सेमी)',
    muac: 'एमयूएसी (सेमी)',
    startAnalysis: 'मल्टीमॉडल विश्लेषण सुरू करा',
    analysisProgress: 'स्क्रीनिंग सिग्नल एकत्र करत आहे...',
    recommendedAction: 'शिफारस केलेले पुढील पाऊल',
    flagReferral: 'पीएचसी (PHC) कडे संदर्भ पाठवा',
    scheduleFollowup: '१४ दिवसांचा फॉलो-अप निश्चित करा',
  },
};

export const getTranslation = (lang: Language, key: string): string => {
  return translations[lang]?.[key] || translations['en']?.[key] || key;
};
