import { Beneficiary } from '../types';

export const INITIAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'BEN-101',
    abhaId: 'ABHA 91-4829-1029-3841',
    rchId: 'RCH-10928471920',
    name: 'Rahul Kumar',
    category: 'child',
    ageYears: 4,
    sex: 'Male',
    guardianName: 'Sunita Kumar',
    locationVillage: 'Ramgarh',
    anganwadiCentreId: 'AWC-1049281',
    phone: '+91 98765 43210',
    anemiaRisk: 'MODERATE',
    nutritionRisk: 'HIGH',
    overallPriority: 'HIGH',
    trajectory: 'DECLINING',
    lastVisitDate: '2026-08-10',
    isDemoData: true,
    visitHistory: [
      {
        id: 'VIS-101-1',
        date: '2026-06-01',
        anemiaRisk: 'LOW',
        nutritionRisk: 'MODERATE',
        overallPriority: 'LOW',
        weightKg: 14.2,
        heightCm: 98,
        muacCm: 13.0,
        imageQuality: 'GOOD',
        recommendedAction: 'Routine Poshan Tracker feeding & 30-day monitoring.',
        notes: 'Child active. Normal conjunctival & palmar chroma.',
      },
      {
        id: 'VIS-101-2',
        date: '2026-07-05',
        anemiaRisk: 'MODERATE',
        nutritionRisk: 'MODERATE',
        overallPriority: 'MODERATE',
        weightKg: 13.8,
        heightCm: 98.5,
        muacCm: 12.2,
        imageQuality: 'GOOD',
        recommendedAction: 'Issue Pink IFA syrup (1ml bi-weekly) & counsel on local iron foods.',
        notes: 'Slight palpebral conjunctival pallor detected.',
      },
      {
        id: 'VIS-101-3',
        date: '2026-08-10',
        anemiaRisk: 'MODERATE',
        nutritionRisk: 'HIGH',
        overallPriority: 'HIGH',
        weightKg: 13.2,
        heightCm: 99.0,
        muacCm: 11.4, // SAM Rule Trigger (<11.5cm)
        imageQuality: 'GOOD',
        recommendedAction: 'Confirmatory Hb testing & Medical Officer referral at PHC Ramgarh.',
        notes: 'MUAC SAM Red Zone trigger. Escalated to Sector Supervisor.',
      },
    ],
  },
  {
    id: 'BEN-102',
    abhaId: 'ABHA 91-3820-9102-4412',
    rchId: 'RCH-10928471988',
    name: 'Ananya',
    category: 'child',
    ageYears: 2,
    ageMonths: 4,
    sex: 'Female',
    guardianName: 'Pooja Rani',
    locationVillage: 'Ramgarh',
    anganwadiCentreId: 'AWC-1049281',
    phone: '+91 98123 45678',
    anemiaRisk: 'LOW',
    nutritionRisk: 'LOW',
    overallPriority: 'LOW',
    trajectory: 'STABLE',
    lastVisitDate: '2026-08-02',
    isDemoData: true,
    visitHistory: [
      {
        id: 'VIS-102-1',
        date: '2026-05-15',
        anemiaRisk: 'LOW',
        nutritionRisk: 'LOW',
        overallPriority: 'LOW',
        weightKg: 11.5,
        heightCm: 86,
        muacCm: 14.1,
        imageQuality: 'GOOD',
        recommendedAction: 'Continue standard Anganwadi Take-Home Ration (THR).',
      },
      {
        id: 'VIS-102-2',
        date: '2026-08-02',
        anemiaRisk: 'LOW',
        nutritionRisk: 'LOW',
        overallPriority: 'LOW',
        weightKg: 12.0,
        heightCm: 88,
        muacCm: 14.3,
        imageQuality: 'GOOD',
        recommendedAction: 'Maintain current growth trajectory. Routine check in 60 days.',
      },
    ],
  },
  {
    id: 'BEN-103',
    abhaId: 'ABHA 91-5510-8821-9012',
    rchId: 'RCH-10928472010',
    name: 'Priya Sharma',
    category: 'pregnant',
    isPregnant: true,
    trimester: 2,
    guardianName: 'Rajesh Sharma',
    locationVillage: 'Chandanpur',
    anganwadiCentreId: 'AWC-1049282',
    phone: '+91 97654 32109',
    anemiaRisk: 'ELEVATED',
    nutritionRisk: 'MODERATE',
    overallPriority: 'HIGH',
    trajectory: 'DECLINING',
    lastVisitDate: '2026-08-12',
    isDemoData: true,
    visitHistory: [
      {
        id: 'VIS-103-1',
        date: '2026-06-12',
        anemiaRisk: 'MODERATE',
        nutritionRisk: 'LOW',
        overallPriority: 'MODERATE',
        weightKg: 52.0,
        heightCm: 156,
        muacCm: 23.5,
        imageQuality: 'GOOD',
        recommendedAction: 'Daily Red IFA tablet & Calcium supplementation under PMSMA.',
      },
      {
        id: 'VIS-103-2',
        date: '2026-08-12',
        anemiaRisk: 'ELEVATED',
        nutritionRisk: 'MODERATE',
        overallPriority: 'HIGH',
        weightKg: 52.8,
        heightCm: 156,
        muacCm: 22.8,
        imageQuality: 'GOOD',
        recommendedAction: 'Urgent confirmatory Hb blood test & Ferritin check at PHC.',
        notes: 'Significant conjunctival pallor increase in 2nd trimester.',
      },
    ],
  },
  {
    id: 'BEN-104',
    abhaId: 'ABHA 91-6623-1109-7721',
    rchId: 'RCH-10928472044',
    name: 'Deepa Devi',
    category: 'pregnant',
    isPregnant: true,
    trimester: 3,
    guardianName: 'Mukesh Devi',
    locationVillage: 'Sonpur',
    anganwadiCentreId: 'AWC-1049283',
    phone: '+91 94567 89012',
    anemiaRisk: 'ELEVATED',
    nutritionRisk: 'HIGH',
    overallPriority: 'HIGH',
    trajectory: 'RAPIDLY_DECLINING',
    lastVisitDate: '2026-08-15',
    isDemoData: true,
    visitHistory: [
      {
        id: 'VIS-104-1',
        date: '2026-07-01',
        anemiaRisk: 'MODERATE',
        nutritionRisk: 'MODERATE',
        overallPriority: 'MODERATE',
        weightKg: 56.0,
        heightCm: 152,
        muacCm: 22.0,
        imageQuality: 'GOOD',
        recommendedAction: 'Supervised IFA dosage & ASHA home visits.',
      },
      {
        id: 'VIS-104-2',
        date: '2026-08-15',
        anemiaRisk: 'ELEVATED',
        nutritionRisk: 'HIGH',
        overallPriority: 'HIGH',
        weightKg: 55.2,
        heightCm: 152,
        muacCm: 20.8,
        imageQuality: 'GOOD',
        recommendedAction: 'Immediate referral to District Hospital for IV Iron Infusion evaluation.',
        notes: '3rd trimester weight loss & severe conjunctival pallor.',
      },
    ],
  },
  {
    id: 'BEN-105',
    abhaId: 'ABHA 91-7712-9901-3341',
    rchId: 'RCH-10928472099',
    name: 'Aarav Patel',
    category: 'child',
    ageYears: 3,
    sex: 'Male',
    guardianName: 'Vikram Patel',
    locationVillage: 'Ramgarh',
    anganwadiCentreId: 'AWC-1049281',
    phone: '+91 93210 98765',
    anemiaRisk: 'LOW',
    nutritionRisk: 'MODERATE',
    overallPriority: 'LOW',
    trajectory: 'IMPROVING',
    lastVisitDate: '2026-08-08',
    isDemoData: true,
    visitHistory: [
      {
        id: 'VIS-105-1',
        date: '2026-05-20',
        anemiaRisk: 'MODERATE',
        nutritionRisk: 'HIGH',
        overallPriority: 'MODERATE',
        weightKg: 11.2,
        heightCm: 91,
        muacCm: 12.0,
        imageQuality: 'GOOD',
        recommendedAction: 'Enrolled in Poshan Tracker intensive care protocol.',
      },
      {
        id: 'VIS-105-2',
        date: '2026-08-08',
        anemiaRisk: 'LOW',
        nutritionRisk: 'MODERATE',
        overallPriority: 'LOW',
        weightKg: 12.8,
        heightCm: 93,
        muacCm: 13.2,
        imageQuality: 'GOOD',
        recommendedAction: 'Positive growth response. Continue monitoring.',
      },
    ],
  },
];
