"""initial migration

Revision ID: 6d91456e8156
Revises: 
Create Date: 2026-08-19 17:14:48.340540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6d91456e8156'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'SUPERVISOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('category', sa.Enum('CHILD', 'PREGNANT_WOMAN', name='beneficiarycategory'), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('trimester', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_category'), 'beneficiaries', ['category'], unique=False)
    op.create_index('ix_beneficiaries_category_dob', 'beneficiaries', ['category', 'date_of_birth'], unique=False)
    op.create_index(op.f('ix_beneficiaries_created_by_id'), 'beneficiaries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_date_of_birth'), 'beneficiaries', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_beneficiaries_name'), 'beneficiaries', ['name'], unique=False)
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='screeningstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_beneficiary_id'), 'screenings', ['beneficiary_id'], unique=False)
    op.create_index('ix_screenings_beneficiary_started', 'screenings', ['beneficiary_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_screenings_completed_at'), 'screenings', ['completed_at'], unique=False)
    op.create_index(op.f('ix_screenings_started_at'), 'screenings', ['started_at'], unique=False)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.create_index(op.f('ix_screenings_worker_id'), 'screenings', ['worker_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='followupstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_assigned_user_id'), 'followups', ['assigned_user_id'], unique=False)
    op.create_index('ix_followups_beneficiary_due', 'followups', ['beneficiary_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_followups_beneficiary_id'), 'followups', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_followups_due_date'), 'followups', ['due_date'], unique=False)
    op.create_index(op.f('ix_followups_screening_id'), 'followups', ['screening_id'], unique=False)
    op.create_index(op.f('ix_followups_status'), 'followups', ['status'], unique=False)
    op.create_index('ix_followups_status_due', 'followups', ['status', 'due_date'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('muac_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_screening_id'), 'measurements', ['screening_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('anemia_risk', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('nutrition_risk', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('overall_priority', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trajectory', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('contributors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_anemia_risk'), 'results', ['anemia_risk'], unique=False)
    op.create_index(op.f('ix_results_nutrition_risk'), 'results', ['nutrition_risk'], unique=False)
    op.create_index(op.f('ix_results_overall_priority'), 'results', ['overall_priority'], unique=False)
    op.create_index(op.f('ix_results_screening_id'), 'results', ['screening_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_screening_id'), table_name='results')
    op.drop_index(op.f('ix_results_overall_priority'), table_name='results')
    op.drop_index(op.f('ix_results_nutrition_risk'), table_name='results')
    op.drop_index(op.f('ix_results_anemia_risk'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_measurements_screening_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_followups_status_due', table_name='followups')
    op.drop_index(op.f('ix_followups_status'), table_name='followups')
    op.drop_index(op.f('ix_followups_screening_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_due_date'), table_name='followups')
    op.drop_index(op.f('ix_followups_beneficiary_id'), table_name='followups')
    op.drop_index('ix_followups_beneficiary_due', table_name='followups')
    op.drop_index(op.f('ix_followups_assigned_user_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_screenings_worker_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_started_at'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_completed_at'), table_name='screenings')
    op.drop_index('ix_screenings_beneficiary_started', table_name='screenings')
    op.drop_index(op.f('ix_screenings_beneficiary_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_beneficiaries_name'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_date_of_birth'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_created_by_id'), table_name='beneficiaries')
    op.drop_index('ix_beneficiaries_category_dob', table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_category'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###