"""initial schema: beneficiaries and visits

Revision ID: 7cf5233ee4a4
Revises: 
Create Date: 2026-08-17 22:55:02.555685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cf5233ee4a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.String(), nullable=False, comment='e.g. B001'),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False, comment='male | female'),
    sa.Column('pregnancy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('muac_mm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('whz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('haz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('waz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('muac_category', sa.String(length=20), nullable=True),
    sa.Column('whz_category', sa.String(length=20), nullable=True),
    sa.Column('haz_category', sa.String(length=20), nullable=True),
    sa.Column('waz_category', sa.String(length=20), nullable=True),
    sa.Column('anemia_ai_risk', sa.String(length=20), nullable=True),
    sa.Column('anemia_ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('anemia_risk', sa.String(length=20), nullable=True),
    sa.Column('nutrition_risk', sa.String(length=20), nullable=True),
    sa.Column('overall_priority', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('trajectory', sa.String(length=30), nullable=True),
    sa.Column('contributors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('recommended_action', sa.String(length=50), nullable=True),
    sa.Column('safety_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('context_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visits_beneficiary_date', 'visits', ['beneficiary_id', 'visit_date'], unique=False)
    op.create_index(op.f('ix_visits_beneficiary_id'), 'visits', ['beneficiary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_beneficiary_id'), table_name='visits')
    op.drop_index('idx_visits_beneficiary_date', table_name='visits')
    op.drop_table('visits')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
